// <auto-generated />
using System;
using ContainerAutomationApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ContainerAutomationApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250706095905_AddLeaveTypeToLeaveRequest")]
    partial class AddLeaveTypeToLeaveRequest
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ContainerAutomationApp.Models.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Password")
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("ContainerAutomationApp.Models.Container", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssignedCraneId")
                        .HasColumnType("int");

                    b.Property<DateTime>("AssignedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ContainerNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Location")
                        .HasColumnType("longtext");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AssignedCraneId");

                    b.ToTable("Containers");
                });

            modelBuilder.Entity("ContainerAutomationApp.Models.Crane", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Cranes");
                });

            modelBuilder.Entity("ContainerAutomationApp.Models.Leave", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LeaveType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("WorkerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WorkerId");

                    b.ToTable("Leaves");
                });

            modelBuilder.Entity("ContainerAutomationApp.Models.LeaveRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LeaveType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("WorkerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WorkerId");

                    b.ToTable("LeaveRequests");
                });

            modelBuilder.Entity("ContainerAutomationApp.Models.Shift", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Shifts");
                });

            modelBuilder.Entity("ContainerAutomationApp.Models.Worker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssignedCraneId")
                        .HasColumnType("int");

                    b.Property<int?>("AssignedShiftId")
                        .HasColumnType("int");

                    b.Property<string>("Certification")
                        .HasColumnType("longtext");

                    b.Property<bool>("LeaveRequest")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AssignedCraneId");

                    b.HasIndex("AssignedShiftId");

                    b.ToTable("Workers");
                });

            modelBuilder.Entity("ContainerAutomationApp.Models.Container", b =>
                {
                    b.HasOne("ContainerAutomationApp.Models.Crane", "AssignedCrane")
                        .WithMany()
                        .HasForeignKey("AssignedCraneId");

                    b.Navigation("AssignedCrane");
                });

            modelBuilder.Entity("ContainerAutomationApp.Models.Leave", b =>
                {
                    b.HasOne("ContainerAutomationApp.Models.Worker", "Worker")
                        .WithMany()
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("ContainerAutomationApp.Models.LeaveRequest", b =>
                {
                    b.HasOne("ContainerAutomationApp.Models.Worker", "Worker")
                        .WithMany()
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("ContainerAutomationApp.Models.Worker", b =>
                {
                    b.HasOne("ContainerAutomationApp.Models.Crane", "AssignedCrane")
                        .WithMany("AssignedWorkers")
                        .HasForeignKey("AssignedCraneId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ContainerAutomationApp.Models.Shift", "AssignedShift")
                        .WithMany()
                        .HasForeignKey("AssignedShiftId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AssignedCrane");

                    b.Navigation("AssignedShift");
                });

            modelBuilder.Entity("ContainerAutomationApp.Models.Crane", b =>
                {
                    b.Navigation("AssignedWorkers");
                });
#pragma warning restore 612, 618
        }
    }
}
