// <auto-generated />
using System;
using ContainerAutomationApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ContainerAutomationApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ContainerAutomationApp.Models.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Password")
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("ContainerAutomationApp.Models.AssignmentHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CraneId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ShiftId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("WorkerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CraneId");

                    b.HasIndex("ShiftId");

                    b.HasIndex("WorkerId");

                    b.ToTable("AssignmentHistories");
                });

            modelBuilder.Entity("ContainerAutomationApp.Models.Container", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssignedCraneId")
                        .HasColumnType("int");

                    b.Property<DateTime>("AssignedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ContainerNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Location")
                        .HasColumnType("longtext");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AssignedCraneId");

                    b.ToTable("Containers");
                });

            modelBuilder.Entity("ContainerAutomationApp.Models.Crane", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Cranes");
                });

            modelBuilder.Entity("ContainerAutomationApp.Models.CraneAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CraneId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ShiftId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CraneId");

                    b.HasIndex("ShiftId");

                    b.ToTable("CraneAssignments");
                });

            modelBuilder.Entity("ContainerAutomationApp.Models.DeletedWorker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Certification")
                        .HasColumnType("longtext");

                    b.Property<string>("Crane")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .HasColumnType("longtext");

                    b.Property<string>("Shift")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("DeletedWorkers");
                });

            modelBuilder.Entity("ContainerAutomationApp.Models.Leave", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LeaveType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("WorkerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WorkerId");

                    b.ToTable("Leaves");
                });

            modelBuilder.Entity("ContainerAutomationApp.Models.LeaveRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LeaveType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("WorkerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WorkerId");

                    b.ToTable("LeaveRequests");
                });

            modelBuilder.Entity("ContainerAutomationApp.Models.Shift", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Shifts");
                });

            modelBuilder.Entity("ContainerAutomationApp.Models.Worker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssignedCraneId")
                        .HasColumnType("int");

                    b.Property<int?>("AssignedShiftId")
                        .HasColumnType("int");

                    b.Property<string>("Certification")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .HasColumnType("longtext");

                    b.Property<int?>("ShiftId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AssignedCraneId");

                    b.HasIndex("AssignedShiftId");

                    b.HasIndex("ShiftId");

                    b.ToTable("Workers");
                });

            modelBuilder.Entity("ContainerAutomationApp.Models.WorkerAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CraneAssignmentId")
                        .HasColumnType("int");

                    b.Property<string>("PunchInTime")
                        .HasColumnType("longtext");

                    b.Property<string>("PunchOutTime")
                        .HasColumnType("longtext");

                    b.Property<TimeSpan>("RestDuration")
                        .HasColumnType("time(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<TimeSpan>("WorkDuration")
                        .HasColumnType("time(6)");

                    b.Property<int>("WorkerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CraneAssignmentId");

                    b.HasIndex("WorkerId");

                    b.ToTable("WorkerAssignments");
                });

            modelBuilder.Entity("ContainerAutomationApp.Models.AssignmentHistory", b =>
                {
                    b.HasOne("ContainerAutomationApp.Models.Crane", "Crane")
                        .WithMany()
                        .HasForeignKey("CraneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ContainerAutomationApp.Models.Shift", "Shift")
                        .WithMany()
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ContainerAutomationApp.Models.Worker", "Worker")
                        .WithMany("History")
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Crane");

                    b.Navigation("Shift");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("ContainerAutomationApp.Models.Container", b =>
                {
                    b.HasOne("ContainerAutomationApp.Models.Crane", "AssignedCrane")
                        .WithMany()
                        .HasForeignKey("AssignedCraneId");

                    b.Navigation("AssignedCrane");
                });

            modelBuilder.Entity("ContainerAutomationApp.Models.CraneAssignment", b =>
                {
                    b.HasOne("ContainerAutomationApp.Models.Crane", "Crane")
                        .WithMany()
                        .HasForeignKey("CraneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ContainerAutomationApp.Models.Shift", "Shift")
                        .WithMany()
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Crane");

                    b.Navigation("Shift");
                });

            modelBuilder.Entity("ContainerAutomationApp.Models.Leave", b =>
                {
                    b.HasOne("ContainerAutomationApp.Models.Worker", "Worker")
                        .WithMany()
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("ContainerAutomationApp.Models.LeaveRequest", b =>
                {
                    b.HasOne("ContainerAutomationApp.Models.Worker", "Worker")
                        .WithMany("LeaveRequests")
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("ContainerAutomationApp.Models.Worker", b =>
                {
                    b.HasOne("ContainerAutomationApp.Models.Crane", "AssignedCrane")
                        .WithMany("AssignedWorkers")
                        .HasForeignKey("AssignedCraneId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ContainerAutomationApp.Models.Shift", "AssignedShift")
                        .WithMany()
                        .HasForeignKey("AssignedShiftId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ContainerAutomationApp.Models.Shift", null)
                        .WithMany("AssignedWorkers")
                        .HasForeignKey("ShiftId");

                    b.Navigation("AssignedCrane");

                    b.Navigation("AssignedShift");
                });

            modelBuilder.Entity("ContainerAutomationApp.Models.WorkerAssignment", b =>
                {
                    b.HasOne("ContainerAutomationApp.Models.CraneAssignment", "CraneAssignment")
                        .WithMany("WorkerAssignments")
                        .HasForeignKey("CraneAssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ContainerAutomationApp.Models.Worker", "Worker")
                        .WithMany()
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CraneAssignment");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("ContainerAutomationApp.Models.Crane", b =>
                {
                    b.Navigation("AssignedWorkers");
                });

            modelBuilder.Entity("ContainerAutomationApp.Models.CraneAssignment", b =>
                {
                    b.Navigation("WorkerAssignments");
                });

            modelBuilder.Entity("ContainerAutomationApp.Models.Shift", b =>
                {
                    b.Navigation("AssignedWorkers");
                });

            modelBuilder.Entity("ContainerAutomationApp.Models.Worker", b =>
                {
                    b.Navigation("History");

                    b.Navigation("LeaveRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
